image: docker:latest

variables:
  API_REPOSITORY_URL: 207259804926.dkr.ecr.us-east-1.amazonaws.com/root/api
  PROXY_REPOSITORY_URL: 207259804926.dkr.ecr.us-east-1.amazonaws.com/root/proxy

services:
- docker:dind

before_script:
  - apk add --update --no-cache build-base python3-dev python3 libffi-dev libressl-dev bash git gettext curl jq
  - curl -O https://bootstrap.pypa.io/get-pip.py
  - python3 get-pip.py
  - pip install awscli

stages:
  - build_api
  - build_proxy

build:
  stage: build_api
  script:
    - $(aws ecr get-login --registry-ids 207259804926 --no-include-email --region us-east-1)
    - docker build -t $API_REPOSITORY_URL:latest . --file ./docker/Dockerfile.api
    - docker push $API_REPOSITORY_URL:latest
  stage: build_proxy
  script:
    - $(aws ecr get-login --registry-ids 207259804926 --no-include-email --region us-east-1)
    - docker build -t $PROXY_REPOSITORY_URL:latest . --file ./docker/Dockerfile.proxy --target copy_flow_proxy_conf_files
    - docker push $PROXY_REPOSITORY_URL:latest
  only:
   - master
   - dockerize
  tags:
    - docker
