services:
  - name: docker:dind
    entrypoint: ["env", "-u", "DOCKER_HOST"]
    command: ["dockerd-entrypoint.sh"]

variables:
  API_REPOSITORY_URL: 207259804926.dkr.ecr.us-east-1.amazonaws.com/root/api
  PROXY_REPOSITORY_URL: 207259804926.dkr.ecr.us-east-1.amazonaws.com/root/proxy
  WEB_REPOSITORY_URL: 207259804926.dkr.ecr.us-east-1.amazonaws.com/root/web
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  # See https://github.com/docker-library/docker/pull/166
  DOCKER_TLS_CERTDIR: ""

stages:
  - build_api
  - build_web

build_api:
  image: docker:latest
  stage: build_api
  before_script:
    - apk add --update --no-cache build-base python3-dev python3 libffi-dev libressl-dev bash git gettext curl jq
    - curl -O https://bootstrap.pypa.io/get-pip.py
    - python3 get-pip.py
    - pip install awscli
  script:
    - $(aws ecr get-login --registry-ids 207259804926 --no-include-email --region us-east-1)
    - >
        docker build .
        --cache-from="API_REPOSITORY_URL:latest"
        -t $API_REPOSITORY_URL:latest
        --file ./docker/Dockerfile.api
    - docker push $API_REPOSITORY_URL:latest

  tags:
    - docker
  only:
      - master
      - dockerize
      
build_web:
  image: docker:latest
  stage: build_web
  before_script:
    - apk add --update --no-cache build-base python3-dev python3 libffi-dev libressl-dev bash git gettext curl jq
    - curl -O https://bootstrap.pypa.io/get-pip.py
    - python3 get-pip.py
    - pip install awscli
  script:
    - $(aws ecr get-login --registry-ids 207259804926 --no-include-email --region us-east-1)
    - >
        docker build .
        --cache-from="WEB_REPOSITORY_URL:latest"
        -t $WEB_REPOSITORY_URL:latest
        --file ./docker/Dockerfile.web
    - docker push $WEB_REPOSITORY_URL:latest

  tags:
    - docker
  only:
      - master
      - dockerize
