services:
  - name: docker:dind
    entrypoint: ["env", "-u", "DOCKER_HOST"]
    command: ["dockerd-entrypoint.sh"]

variables:
  DOCKER_HOST: tcp://docker:2375

stages:
  - test

include:
  - "/api/.gitlab-ci.yml"
  - "/web/.gitlab-ci.yml"
