variables:
  API_REPOSITORY_URL: 207259804926.dkr.ecr.us-east-1.amazonaws.com/root/api
  PROXY_REPOSITORY_URL: 207259804926.dkr.ecr.us-east-1.amazonaws.com/root/proxy
  WEB_REPOSITORY_URL: 207259804926.dkr.ecr.us-east-1.amazonaws.com/root/web

stages:
  - heroku_api_deploy
  - build_api

build_api:
  image: docker:latest
  stage: build_api
  before_script:
    - apk add --update --no-cache build-base python3-dev python3 libffi-dev libressl-dev bash git gettext curl jq
    - curl -O https://bootstrap.pypa.io/get-pip.py
    - python3 get-pip.py
    - pip install awscli
  script:
    - $(aws ecr get-login --registry-ids 207259804926 --no-include-email --region us-east-1)
    - >
        docker build .
        --cache-from="API_REPOSITORY_URL:latest"
        -t $API_REPOSITORY_URL:latest
        --file ./docker/Dockerfile.api
    - docker push $API_REPOSITORY_URL:latest

heroku_api_deploy:
  image: node:12.16.2
  before_script:
    - apt-get install git
  type: deploy
  stage: heroku_api_deploy
  script:
      - apt-get update -qy
      - apt-get install -y ruby-dev
      - gem install dpl
#      - dpl --provider=heroku --app=cv-root-staging --api-key=$HEROKU_API_KEY
  only:
      - master
      - dockerize
