version: 0.2
env:
  variables:
    AWS_REGION: eu-west-1
    API_REPOSITORY: rootspace_ecr/api
    WEB_REPOSITORY: rootspace_ecr/web
#   parameter-store:
#     ENV: "ENV"
#   # Export vars to CodePipeline
#   exported-variables:
#     - ENV
#     - API_URL
phases:
    # install:
    #     commands:
    #         - echo Starting the Docker daemon...
    #         - /usr/local/bin/dockerd-entrypoint.sh
    pre_build:
        commands:
            - aws --version
            - docker --version
    build:
        commands:
            #
            # .ENV foe WEB
            #
            - pwd
            - cd web
            - 'echo VUE_APP_API_URL=https//api:3001>>./.env'
            - 'echo VUE_APP_PORT=3000>>./.env'
            - 'echo VUE_APP_YWS_URL=ws://localhost:6001>>./.env'
            #
            # Docker for WEB
            #
            - cd $CODEBUILD_SRC_DIR
            - pwd
            - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 207259804926.dkr.ecr.$AWS_REGION.amazonaws.com
            - aws ecr create-repository --repository-name $WEB_REPOSITORY --region $AWS_REGION || true
            - docker build .
              --cache-from="207259804926.dkr.ecr.$AWS_REGION.amazonaws.com/rootspace_ecr/web:latest"
              --tag 207259804926.dkr.ecr.$AWS_REGION.amazonaws.com/rootspace_ecr/web:latest
              --file ./infra/docker/Dockerfile.web
            - docker push 207259804926.dkr.ecr.$AWS_REGION.amazonaws.com/rootspace_ecr/web:latest
    post_build:
        commands:
            - 'pwd'
