version: "3.7"

services:
  htpasswd:
    image: registry:latest
    container_name: root_htpasswd_nomad
    hostname: root_htpasswd_nomad
    volumes:
      - root_htpasswd:/etc/htpasswd:rw
    command: ["htpasswd", "-cBbd", "/etc/htpasswd/.htpasswd", "nomad", "67ce7dd7dAa28f4835915d3c7fbfA27a4a8c83c1380f157453b469de01813c228_2020"]
  proxy_nomad:
    container_name: root_proxy_nomad
    hostname: root_proxy_nomad
    image: root_proxy_nomad:latest # name for the custom built image
    network_mode: "host"
    build:
      context: .
      dockerfile: ./docker/Dockerfile.proxy
      target: nomad
    volumes:
     - root_letsencrypt:/etc/letsencrypt:rw
     - root_htpasswd:/etc/htpasswd:ro
     - root_certbot:/var/www/certbot:rw
    ports:
     - "8080:80"
    restart: always
    environment:
     - NOMAD_HOST=nomad.root.prod.clearviewdev.io
     - CONSUL_HOST=consul.root.prod.clearviewdev.io
    command: "/bin/sh -c 'while :; do sleep 5m & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'" # CERTBOT

volumes:
  root_letsencrypt:
    name: root_letsencrypt
  root_htpasswd:
    name: root_htpasswd
  root_certbot:
    name: root_certbot
