FROM node:16 as build
MAINTAINER nedim@clearview.team
WORKDIR /srv

COPY ./web/. ./web/
COPY ./infra/. ./infra/

RUN cd web && \
    echo "Installing packages... $(yarn install)" && \
    echo "Building web...  $(yarn build)"

FROM nginx:1.22 as infra
WORKDIR /srv
RUN apt-get update && apt-get install netcat -yq

COPY --from=build /srv/infra/docker/web/nginx/nginx.conf /etc/nginx/nginx.conf
COPY --from=build /srv/infra/docker/web/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /srv/infra/docker/web/nginx/conf.d/* /etc/nginx/conf.d/
COPY --from=build /srv/infra/docker/web/entrypoint.sh /entrypoint.sh

FROM infra as nginx
COPY --from=build /srv/web /srv/web

RUN ["chmod", "+x", "/entrypoint.sh"]

RUN ls web

ENTRYPOINT ["/entrypoint.sh"]

CMD ["nginx", "-g", "daemon off;"]
