kind: PersistentVolume
apiVersion: v1
metadata:
  name: root-postgres-pv-volume
  namespace: root
  labels:
    type: local
    app: root-postgres
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: "Delete" #  Retain Recycle Delete
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data_root"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: root-postgres-pv-claim
  namespace: root
  labels:
    app: root-postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
