export const FilteredKey = Symbol('filtered')
export const ArchivedViewKey = Symbol('archivedView')
export const TaskId = Symbol('taskId')
export const YDoc = Symbol('ydoc')
export const ClientID = Symbol('clientId')
