test-build-api:
  image: node:12.16
  stage: test
  only:
    refs:
      - merge_requests
    changes:
      - api/**/*
  before_script:
    - apt-get install rsync
    - cd api
    - yarn
  script:
    - yarn build

test-tslint-api:
  image: node:12.16
  stage: test
  only:
    refs:
      - merge_requests
    changes:
      - api/**/*
  before_script:
    - cd api
    - yarn
  script:
    - yarn tslint
